/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAwardsRouteImport } from './routes/admin/awards'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminPatentsRouteImport } from './routes/admin/patents'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPublicationsRouteImport } from './routes/admin/publications'
import { Route as AdminSkillsRouteImport } from './routes/admin/skills'
import { Route as AdminTimelineRouteImport } from './routes/admin/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatentsRoute = AdminPatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicationsRoute = AdminPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimelineRoute = AdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/awards'
    | '/admin/gallery'
    | '/admin/patents'
    | '/admin/profile'
    | '/admin/publications'
    | '/admin/skills'
    | '/admin/timeline'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/awards'
    | '/admin/gallery'
    | '/admin/patents'
    | '/admin/profile'
    | '/admin/publications'
    | '/admin/skills'
    | '/admin/timeline'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/awards'
    | '/admin/gallery'
    | '/admin/patents'
    | '/admin/profile'
    | '/admin/publications'
    | '/admin/skills'
    | '/admin/timeline'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patents': {
      id: '/admin/patents'
      path: '/patents'
      fullPath: '/admin/patents'
      preLoaderRoute: typeof AdminPatentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publications': {
      id: '/admin/publications'
      path: '/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AdminPublicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timeline': {
      id: '/admin/timeline'
      path: '/timeline'
      fullPath: '/admin/timeline'
      preLoaderRoute: typeof AdminTimelineRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminPatentsRoute: typeof AdminPatentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminPublicationsRoute: typeof AdminPublicationsRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminTimelineRoute: typeof AdminTimelineRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAwardsRoute: AdminAwardsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminPatentsRoute: AdminPatentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminPublicationsRoute: AdminPublicationsRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminTimelineRoute: AdminTimelineRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
